name: Build Flite TTS APK

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Set up Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 12266719 # Default version 16.0
          packages: tools platform-tools build-tools;30.0.3 platforms;android-22

      # Step 4: Set up Android NDK
      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21e
          link-to-sdk: true

      # Step 5: Export Environment Variables
      - name: Export Environment Variables
        run: |
          echo "ANDROID_NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV

      # Step 6: Run the build script
      - name: Build APK
        run: |
          chmod +x ./build.sh
          ./build.sh

      # Step 7: Upload APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: FliteEngine-debug-apk
          path: bin/FliteEngine-debug.apk

